#!/usr/bin/env bash
# ── AEGIS SaaS — On-Premise Installer ───────────────────────
# Automated installation script for deploying AEGIS in a client environment.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/laral5173/aegis-itsm-agent/main/install.sh | bash
#   # or locally:
#   chmod +x install.sh && ./install.sh
#
# Supports:
#   - Local LLM (Ollama) — no API key needed
#   - External API (DeepSeek, OpenAI, etc.) — requires API key
#
# Environment variables (optional):
#   LLM_PROVIDER    = "ollama" | "deepseek" | "openai"   (default: ollama)
#   DEEPSEEK_API_KEY = your DeepSeek API key
#   OPENAI_API_KEY   = your OpenAI API key
#   OLLAMA_MODEL     = model name for Ollama (default: llama3)
#   AEGIS_DOMAIN     = domain for HTTPS (default: localhost)
#   LOG_LEVEL        = DEBUG | INFO | WARNING | ERROR (default: INFO)
# =============================================================

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info()  { echo -e "${BLUE}[INFO]${NC}  $1"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ── Banner ──────────────────────────────────────────────────
echo ""
echo "  ╔═══════════════════════════════════════════╗"
echo "  ║         AEGIS — On-Premise Installer      ║"
echo "  ║   Autonomous Incident Triage Agent        ║"
echo "  ╚═══════════════════════════════════════════╝"
echo ""

# ── Step 1: Check Prerequisites ────────────────────────────
log_info "Step 1/5: Checking prerequisites..."

# Check Docker
if ! command -v docker &> /dev/null; then
    log_error "Docker is not installed."
    echo "  Install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi
log_ok "Docker found: $(docker --version)"

# Check Docker Compose
if ! docker compose version &> /dev/null; then
    log_error "Docker Compose is not installed."
    echo "  Install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi
log_ok "Docker Compose found: $(docker compose version)"

# Check RAM (recommended: 4GB+)
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    total_ram_kb=$(grep MemTotal /proc/meminfo | awk '{print $2}')
    total_ram_gb=$((total_ram_kb / 1024 / 1024))
    if [ "$total_ram_gb" -lt 4 ]; then
        log_warn "System has ${total_ram_gb}GB RAM. 4GB+ recommended for Ollama."
    else
        log_ok "RAM: ${total_ram_gb}GB"
    fi
fi

# Check for NVIDIA GPU (optional)
if command -v nvidia-smi &> /dev/null; then
    gpu_info=$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null | head -1)
    log_ok "NVIDIA GPU detected: ${gpu_info:-yes}"
else
    log_warn "No NVIDIA GPU detected. Ollama will run on CPU (slower)."
fi

# ── Step 2: Configure LLM Provider ──────────────────────────
log_info "Step 2/5: Configuring LLM provider..."

LLM_PROVIDER="${LLM_PROVIDER:-ollama}"

case "$LLM_PROVIDER" in
    ollama)
        log_info "Using local Ollama (no API key needed)"
        OLLAMA_MODEL="${OLLAMA_MODEL:-llama3}"
        log_info "  Model: ${OLLAMA_MODEL}"
        ;;
    deepseek)
        if [ -z "${DEEPSEEK_API_KEY:-}" ]; then
            log_error "DEEPSEEK_API_KEY is not set."
            echo "  Usage: DEEPSEEK_API_KEY=sk-xxx ./install.sh"
            echo "  Or:    export DEEPSEEK_API_KEY=sk-xxx && ./install.sh"
            exit 1
        fi
        log_ok "DeepSeek API key configured"
        ;;
    openai)
        if [ -z "${OPENAI_API_KEY:-}" ]; then
            log_error "OPENAI_API_KEY is not set."
            echo "  Usage: OPENAI_API_KEY=sk-xxx ./install.sh"
            echo "  Or:    export OPENAI_API_KEY=sk-xxx && ./install.sh"
            exit 1
        fi
        log_ok "OpenAI API key configured"
        ;;
    *)
        log_error "Unknown LLM_PROVIDER: ${LLM_PROVIDER}"
        echo "  Valid options: ollama, deepseek, openai"
        exit 1
        ;;
esac

# ── Step 3: Create .env file ────────────────────────────────
log_info "Step 3/5: Creating .env configuration..."

if [ -f .env ]; then
    log_warn ".env file already exists. Creating .env.aegis instead."
    ENV_FILE=".env.aegis"
else
    ENV_FILE=".env"
fi

cat > "$ENV_FILE" <<EOF
# AEGIS Configuration
# Generated by install.sh on $(date)

# LLM Provider: ollama | deepseek | openai
LLM_PROVIDER=${LLM_PROVIDER}

EOF

if [ "$LLM_PROVIDER" = "deepseek" ]; then
    echo "DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}" >> "$ENV_FILE"
elif [ "$LLM_PROVIDER" = "openai" ]; then
    echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> "$ENV_FILE"
elif [ "$LLM_PROVIDER" = "ollama" ]; then
    cat >> "$ENV_FILE" <<EOF
OLLAMA_BASE_URL=http://ollama:11434
OLLAMA_MODEL=${OLLAMA_MODEL}
EOF
fi

cat >> "$ENV_FILE" <<EOF

# Database (defaults are fine for single-node deployment)
DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/aegis

# ChromaDB (RAG vector store)
CHROMA_HOST=chromadb
CHROMA_PORT=8000
CHROMA_USE_SERVER=true

# Security
AUTH_REQUIRED=false

# Logging
LOG_LEVEL=${LOG_LEVEL:-INFO}
EOF

log_ok "Configuration written to ${ENV_FILE}"

# ── Step 4: Pull Docker images ──────────────────────────────
log_info "Step 4/5: Pulling Docker images..."

docker compose --env-file "$ENV_FILE" pull postgres chromadb app 2>&1 | tail -5

if [ "$LLM_PROVIDER" = "ollama" ]; then
    log_info "Pulling Ollama image..."
    docker compose --profile ollama --env-file "$ENV_FILE" pull ollama 2>&1 | tail -3
fi

log_ok "Docker images pulled"

# ── Step 5: Start AEGIS ─────────────────────────────────────
log_info "Step 5/5: Starting AEGIS..."

COMPOSE_FLAGS="--env-file ${ENV_FILE}"

if [ "$LLM_PROVIDER" = "ollama" ]; then
    COMPOSE_FLAGS="${COMPOSE_FLAGS} --profile ollama"
fi

if [ -n "${AEGIS_DOMAIN:-}" ]; then
    COMPOSE_FLAGS="${COMPOSE_FLAGS} --profile caddy"
    export CADDY_DOMAIN="${AEGIS_DOMAIN}"
fi

log_info "Starting containers (this may take a minute)..."
docker compose ${COMPOSE_FLAGS} up --build -d 2>&1 | tail -5

# ── Wait for health ─────────────────────────────────────────
log_info "Waiting for AEGIS to be ready..."
for i in $(seq 1 30); do
    if curl -s http://localhost:8000/v1/health > /dev/null 2>&1; then
        log_ok "AEGIS is ready!"
        break
    fi
    if [ "$i" -eq 30 ]; then
        log_warn "Timed out waiting for AEGIS. Check logs: docker compose logs app"
    fi
    sleep 2
done

# ── Initialize Knowledge Base (RAG) ─────────────────────────
log_info "Initializing knowledge base..."
docker compose ${COMPOSE_FLAGS} exec -T app python scripts/init_knowledge_base.py 2>&1 || true

# ── Summary ─────────────────────────────────────────────────
echo ""
echo "  ╔═══════════════════════════════════════════╗"
echo "  ║         AEGIS Installation Complete!      ║"
echo "  ╚═══════════════════════════════════════════╝"
echo ""
echo "  Access AEGIS at:"
echo "    API:      http://localhost:8000"
echo "    Health:   http://localhost:8000/v1/health"
echo "    Docs:     http://localhost:8000/docs"
echo ""

if [ -n "${AEGIS_DOMAIN:-}" ]; then
    echo "    HTTPS:    https://${AEGIS_DOMAIN}"
    echo ""
fi

echo "  LLM Provider: ${LLM_PROVIDER}"
if [ "$LLM_PROVIDER" = "ollama" ]; then
    echo "  Model:       ${OLLAMA_MODEL}"
    echo ""
    echo "  NOTE: The first LLM request may be slow while Ollama"
    echo "  loads the model into memory. Subsequent requests"
    echo "  will be faster."
fi
echo ""
echo "  To view logs:  docker compose logs -f app"
echo "  To stop:       docker compose down"
echo "  To update:     docker compose pull && docker compose up -d"
echo ""
