# ── AEGIS SaaS — On-Premise Installer (Windows) ──────────────
# Automated installation script for deploying AEGIS in a client environment.
#
# Usage:
#   .\install.ps1
#   # or with API key:
#   $env:LLM_PROVIDER="deepseek"; $env:DEEPSEEK_API_KEY="sk-xxx"; .\install.ps1
#
# Supports:
#   - Local LLM (Ollama) — no API key needed
#   - External API (DeepSeek, OpenAI, etc.) — requires API key
#
# Environment variables (optional):
#   LLM_PROVIDER    = "ollama" | "deepseek" | "openai"   (default: ollama)
#   DEEPSEEK_API_KEY = your DeepSeek API key
#   OPENAI_API_KEY   = your OpenAI API key
#   OLLAMA_MODEL     = model name for Ollama (default: llama3)
#   AEGIS_DOMAIN     = domain for HTTPS (default: localhost)
#   LOG_LEVEL        = DEBUG | INFO | WARNING | ERROR (default: INFO)
# =============================================================

$ErrorActionPreference = "Stop"

# ── Colors ──────────────────────────────────────────────────
$Host.UI.RawUI.ForegroundColor = "Cyan"
Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════╗"
Write-Host "  ║         AEGIS — On-Premise Installer      ║"
Write-Host "  ║   Autonomous Incident Triage Agent        ║"
Write-Host "  ╚═══════════════════════════════════════════╝"
Write-Host ""
$Host.UI.RawUI.ForegroundColor = "White"

function Write-Info  { Write-Host "[INFO]  $args" -ForegroundColor Cyan }
function Write-Ok    { Write-Host "[OK]    $args" -ForegroundColor Green }
function Write-Warn  { Write-Host "[WARN]  $args" -ForegroundColor Yellow }
function Write-Error { Write-Host "[ERROR] $args" -ForegroundColor Red }

# ── Step 1: Check Prerequisites ────────────────────────────
Write-Info "Step 1/5: Checking prerequisites..."

# Check Docker
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Error "Docker is not installed."
    Write-Host "  Install Docker Desktop: https://docs.docker.com/get-docker/"
    exit 1
}
Write-Ok "Docker found: $(docker --version)"

# Check Docker Compose
if (-not (docker compose version 2>$null)) {
    Write-Error "Docker Compose is not installed."
    exit 1
}
Write-Ok "Docker Compose found: $(docker compose version)"

# Check for NVIDIA GPU (optional)
if (Get-Command nvidia-smi -ErrorAction SilentlyContinue) {
    Write-Ok "NVIDIA GPU detected"
} else {
    Write-Warn "No NVIDIA GPU detected. Ollama will run on CPU (slower)."
}

# ── Step 2: Configure LLM Provider ──────────────────────────
Write-Info "Step 2/5: Configuring LLM provider..."

$LLM_PROVIDER = if ($env:LLM_PROVIDER) { $env:LLM_PROVIDER } else { "ollama" }

switch ($LLM_PROVIDER) {
    "ollama" {
        Write-Info "Using local Ollama (no API key needed)"
        $OLLAMA_MODEL = if ($env:OLLAMA_MODEL) { $env:OLLAMA_MODEL } else { "llama3" }
        Write-Info "  Model: $OLLAMA_MODEL"
    }
    "deepseek" {
        if (-not $env:DEEPSEEK_API_KEY) {
            Write-Error "DEEPSEEK_API_KEY is not set."
            Write-Host "  Usage: `$env:DEEPSEEK_API_KEY='sk-xxx'; .\install.ps1"
            exit 1
        }
        Write-Ok "DeepSeek API key configured"
    }
    "openai" {
        if (-not $env:OPENAI_API_KEY) {
            Write-Error "OPENAI_API_KEY is not set."
            Write-Host "  Usage: `$env:OPENAI_API_KEY='sk-xxx'; .\install.ps1"
            exit 1
        }
        Write-Ok "OpenAI API key configured"
    }
    default {
        Write-Error "Unknown LLM_PROVIDER: $LLM_PROVIDER"
        Write-Host "  Valid options: ollama, deepseek, openai"
        exit 1
    }
}

# ── Step 3: Create .env file ────────────────────────────────
Write-Info "Step 3/5: Creating .env configuration..."

$ENV_FILE = if (Test-Path .env) { ".env.aegis" } else { ".env" }

@"
# AEGIS Configuration
# Generated by install.ps1 on $(Get-Date)

# LLM Provider: ollama | deepseek | openai
LLM_PROVIDER=${LLM_PROVIDER}

"@ | Out-File -FilePath $ENV_FILE -Encoding UTF8

if ($LLM_PROVIDER -eq "deepseek") {
    Add-Content $ENV_FILE "DEEPSEEK_API_KEY=$env:DEEPSEEK_API_KEY"
} elseif ($LLM_PROVIDER -eq "openai") {
    Add-Content $ENV_FILE "OPENAI_API_KEY=$env:OPENAI_API_KEY"
} elseif ($LLM_PROVIDER -eq "ollama") {
    Add-Content $ENV_FILE @"
OLLAMA_BASE_URL=http://ollama:11434
OLLAMA_MODEL=${OLLAMA_MODEL}
"@
}

Add-Content $ENV_FILE @"

# Database (defaults are fine for single-node deployment)
DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/aegis

# ChromaDB (RAG vector store)
CHROMA_HOST=chromadb
CHROMA_PORT=8000
CHROMA_USE_SERVER=true

# Security
AUTH_REQUIRED=false

# Logging
LOG_LEVEL=$(if ($env:LOG_LEVEL) { $env:LOG_LEVEL } else { "INFO" })
"@

Write-Ok "Configuration written to $ENV_FILE"

# ── Step 4: Pull Docker images ──────────────────────────────
Write-Info "Step 4/5: Pulling Docker images..."

docker compose --env-file "$ENV_FILE" pull postgres chromadb app 2>&1 | Select-Object -Last 5

if ($LLM_PROVIDER -eq "ollama") {
    Write-Info "Pulling Ollama image..."
    docker compose --profile ollama --env-file "$ENV_FILE" pull ollama 2>&1 | Select-Object -Last 3
}

Write-Ok "Docker images pulled"

# ── Step 5: Start AEGIS ─────────────────────────────────────
Write-Info "Step 5/5: Starting AEGIS..."

$COMPOSE_FLAGS = "--env-file $ENV_FILE"

if ($LLM_PROVIDER -eq "ollama") {
    $COMPOSE_FLAGS = "$COMPOSE_FLAGS --profile ollama"
}

if ($env:AEGIS_DOMAIN) {
    $COMPOSE_FLAGS = "$COMPOSE_FLAGS --profile caddy"
    $env:CADDY_DOMAIN = $env:AEGIS_DOMAIN
}

Write-Info "Starting containers (this may take a minute)..."
docker compose $COMPOSE_FLAGS up --build -d 2>&1 | Select-Object -Last 5

# ── Wait for health ─────────────────────────────────────────
Write-Info "Waiting for AEGIS to be ready..."
for ($i = 0; $i -lt 30; $i++) {
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:8000/v1/health" -UseBasicParsing -TimeoutSec 2
        if ($response.StatusCode -eq 200) {
            Write-Ok "AEGIS is ready!"
            break
        }
    } catch {
        # Not ready yet
    }
    if ($i -eq 29) {
        Write-Warn "Timed out waiting for AEGIS. Check logs: docker compose logs app"
    }
    Start-Sleep -Seconds 2
}

# ── Initialize Knowledge Base (RAG) ─────────────────────────
Write-Info "Initializing knowledge base..."
docker compose $COMPOSE_FLAGS exec -T app python scripts/init_knowledge_base.py 2>&1 | Out-Null

# ── Summary ─────────────────────────────────────────────────
$Host.UI.RawUI.ForegroundColor = "Cyan"
Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════╗"
Write-Host "  ║         AEGIS Installation Complete!      ║"
Write-Host "  ╚═══════════════════════════════════════════╝"
Write-Host ""
$Host.UI.RawUI.ForegroundColor = "White"
Write-Host "  Access AEGIS at:"
Write-Host "    API:      http://localhost:8000"
Write-Host "    Health:   http://localhost:8000/v1/health"
Write-Host "    Docs:     http://localhost:8000/docs"
Write-Host ""

if ($env:AEGIS_DOMAIN) {
    Write-Host "    HTTPS:    https://$env:AEGIS_DOMAIN"
    Write-Host ""
}

Write-Host "  LLM Provider: $LLM_PROVIDER"
if ($LLM_PROVIDER -eq "ollama") {
    Write-Host "  Model:       $OLLAMA_MODEL"
    Write-Host ""
    Write-Host "  NOTE: The first LLM request may be slow while Ollama"
    Write-Host "  loads the model into memory. Subsequent requests"
    Write-Host "  will be faster."
}
Write-Host ""
Write-Host "  To view logs:  docker compose logs -f app"
Write-Host "  To stop:       docker compose down"
Write-Host "  To update:     docker compose pull && docker compose up -d"
Write-Host ""
